### post 1
POST https://isnft-prod.azurewebsites.net/api/users HTTP/1.1
Content-Type: application/json
Authorization: Hola

{
      "email": "test1@gm.com",
      "password": "Hola",
      "person": {
        "birthday": "10-10-1929",
        "cityId": 1,
        "lastName": "dqwq",
        "name": "data.name",
        "phone": "data.phone",
      },
      "userName": "data.userName",
}

### GET 
DELETE  https://isnft-prod.azurewebsites.net/api/houses/12
Content-Type: application/json
Authorization: Hola
